### PR TITLE
Update gentx-kynraze.json

### PR DESCRIPTION
**Pull request by kynraze**

### CODE REVIEW

**Review by benjnp — APPROVED** [review]
Please change the amount from 100,000 to 10,000 BCX

**Comment by kynraze** [comment]
> Please change the amount from 100,000 to 10,000 BCX

I have made the changes.

**Review by benjnp — COMMENTED** [review]
Still having errors upon adding this gentx. Have you tried it locally?
The balance is now ok but somehow the signature in the gentx is not compatible.
Try to download the current genesis.json first
https://github.com/BlockXLabs/networks/blob/master/chains/blockx_100-1/genesis.json

then add your gentx
then blockxd collect-gentxs
then blockxd start

Please try if you won't encounter any issues.

Thanks

**Comment by kynraze** [comment]
> Still having errors upon adding this gentx. Have you tried it locally? The balance is now ok but somehow the signature in the gentx is not compatible. Try to download the current genesis.json first https://github.com/BlockXLabs/networks/blob/master/chains/blockx_100-1/genesis.json
> 
> then add your gentx then blockxd collect-gentxs then blockxd start
> 
> Please try if you won't encounter any issues.
> 
> Thanks

I tried it locally, and it's working fine.

**Comment by kynraze** [comment]
> > Still having errors upon adding this gentx. Have you tried it locally? The balance is now ok but somehow the signature in the gentx is not compatible. Try to download the current genesis.json first https://github.com/BlockXLabs/networks/blob/master/chains/blockx_100-1/genesis.json
> > then add your gentx then blockxd collect-gentxs then blockxd start
> > Please try if you won't encounter any issues.
> > Thanks
> 
> I tried it locally, and it's working fine.

but I need to blockxd add-genesis-account your-key-name 10000000000000000000000abcx before collect the gentx

```11:10AM INF This node is a validator addr=859400F84B0E9E33C7B17933FFC94156D9434EB2 module=consensus pubKey=r/fT4lsMbsv2GcpTBZAA46MvzlkN8QGWKFMFPIeGCRA= server=node
11:10AM INF P2P Node ID ID=9c94eecf1d686e53db026789e06da7db848816fc file=/home/blockx/.blockxd/config/node_key.json module=p2p server=node
11:10AM INF Adding persistent peers addrs=[] module=p2p server=node
11:10AM INF Adding unconditional peer ids ids=[] module=p2p server=node
11:10AM INF Add our address to book addr={"id":"9c94eecf1d686e53db026789e06da7db848816fc","ip":"0.0.0.0","port":23656} book=/home/blockx/.blockxd/config/addrbook.json module=p2p server=node
11:10AM INF service start impl=Node msg={} server=node
11:10AM INF Genesis time is in the future. Sleeping until then... genTime=2024-01-15T08:30:00Z server=node
11:10AM INF Starting pprof server laddr=localhost:23060 server=node```

**Comment by benjnp** [comment]
Yes you'll need to do something like 
blockxd add-genesis-account blockx10tw3yt9vthc6enh8p9muryajnz8y7psh7wuldn 100000000000000000000000abcx --keyring-backend file

**Comment by kynraze** [comment]
> Yes you'll need to do something like blockxd add-genesis-account blockx10tw3yt9vthc6enh8p9muryajnz8y7psh7wuldn 100000000000000000000000abcx --keyring-backend file

Yes, I have already done that and collected the gentx. It's working fine. Do I need to resubmit?

**Comment by benjnp** [comment]
But when you tried it, did you try to use with this genesis?
https://github.com/BlockXLabs/networks/blob/master/chains/blockx_100-1/genesis.json

Because when I tried to add your gentx to this existing genesis file, it presents an error.

**Comment by kynraze** [comment]
Yes, I followed your guide. I removed the genesis, downloaded it from above, added the genesis account, collected gentxs, tried to start, and it's working.

**Comment by kynraze** [comment]
let me created a new gentx then

**Comment by kynraze** [comment]
I have made changes

```1:17PM INF This node is a validator addr=B6536110165787DE8D0DD29E02010C1616AFC0A8 module=consensus pubKey=LHAeTzhqVEKrXegLf/1KlD0t1N1crcAqYjgqR16eq9Y= server=node
1:17PM INF P2P Node ID ID=1d8945e8c77ea3a8d448c7fe77adef4088458af4 file=/home/blockx/.blockxd/config/node_key.json module=p2p server=node
1:17PM INF Adding persistent peers addrs=[] module=p2p server=node
1:17PM INF Adding unconditional peer ids ids=[] module=p2p server=node
1:17PM INF Add our address to book addr={"id":"1d8945e8c77ea3a8d448c7fe77adef4088458af4","ip":"0.0.0.0","port":23656} book=/home/blockx/.blockxd/config/addrbook.json module=p2p server=node
1:17PM INF service start impl=Node msg={} server=node
1:17PM INF Genesis time is in the future. Sleeping until then... genTime=2024-01-15T12:00:01Z server=node
1:17PM INF Starting pprof server laddr=localhost:23060 server=node```

**Review by benjnp — APPROVED** [review]

**Pull request merged**
