### PR TITLE
Update gentx-Hexnodes.json

### PR DESCRIPTION
**Pull request by hexskrt**

### CODE REVIEW

**Comment by benjnp** [comment]
Still having errors upon adding this gentx. Have you tried it locally?
Try to download the current genesis.json first 
https://github.com/BlockXLabs/networks/blob/master/chains/blockx_100-1/genesis.json

then add your gentx
then blockxd collect-gentxs
then blockxd start

Please try if you won't encounter any issues.

Thanks

**Comment by hexskrt** [comment]
i fixed it, can you check again please?

**Review by benjnp — COMMENTED** [review]
I think you pasted it incorrectly, in the JSON file submitted there is this one
co","details":"Staking Serv{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Hexnodes","identity":"5CD9816C37D32C5B","website":"https://hexnodes.co","security_contact":"contact@hexnodes.co","details":"Staking Service Provider | We Validate, You Levitate"},"commission":

**Comment by hexskrt** [comment]
fixed sorry

**Review by benjnp — APPROVED** [review]

**Pull request merged**
