### PR TITLE
Creat by OneNov

### PR DESCRIPTION
**Pull request by OneNov0209**

### CODE REVIEW

**Review by benjnp — COMMENTED** [review]
I tried to add it to the main genesis file but it produced an error. Did you try it on your local machine?

**Comment by OneNov0209** [comment]
no, i add in vps

**Comment by OneNov0209** [comment]
this, need git push?

**Comment by benjnp** [comment]
I mean did it work together with the genesis as this one?
https://github.com/BlockXLabs/networks/blob/master/chains/blockx_100-1/genesis.json

**Comment by OneNov0209** [comment]
Screenshot 2024-01-12 235542
this?

**Comment by benjnp** [comment]
Try to do a blockxd start after issuing the add account and blockxd collect-gentxs with your gentx included

**Comment by OneNov0209** [comment]
should I delete genesis.json? then replace it with gentX?

**Comment by benjnp** [comment]
Replace your genesis file with this one (https://github.com/BlockXLabs/networks/blob/master/chains/blockx_100-1/genesis.json). Then do a 
blockxd add-genesis-account{your address} 100000000000000000000000abcx --keyring-backend file

Then if you have your gentx with you, do a 'blockxd collect-gentxs' command.

Once all done then do a blockxd start, see what will happen. 
It should show something like this
3:14PM INF Genesis time is in the future. Sleeping until then... genTime=2024-01-15T12:00:01Z server=node
3:14PM INF Starting pprof server laddr=localhost:6060 server=node

**Comment by OneNov0209** [comment]
Screenshot 2024-01-13 000424
like this

**Comment by benjnp** [comment]
Did you do the collect-gentxs command prior to that?
Try to clear your data folder by going to .blockxd/data
Remove everything except the priv_validator_state.json
Then check your priv_validator_state.json, make sure it only has this
{
  "height": "0",
  "round": 0,
  "step": 0
}

Then try to run blockxd start again

**Comment by OneNov0209** [comment]
ok  wil try

**Comment by OneNov0209** [comment]
Screenshot 2024-01-13 002524
this right?

**Comment by OneNov0209** [comment]
Screenshot 2024-01-13 002809
already sleep

**Comment by benjnp** [comment]
Yes, did you clear the data folder before you run it? If so, submit the gentx that you used

**Comment by OneNov0209** [comment]
Screenshot 2024-01-13 003514
Yes, that's right, I deleted it first, then left the priv_validator file. and now I see on gentX it looks default, do I have to edit like before?

**Comment by benjnp** [comment]
You can change the details if you want

**Comment by OneNov0209** [comment]
ok done,, and now need create new PR?

**Comment by benjnp** [comment]
Yes please resubmit your gentx

**Comment by OneNov0209** [comment]
ok

**Review by benjnp — COMMENTED** [review]
It didn't work. Can you try to clear your data folder again except the priv_validator? 

cd /root/.blockxd/data
rm -vr !(priv_validator_state.json)

Then after you do that, type blockxd start then paste me the result. Also, can you upload your generated genesis.json file as well that you're using so I can compare it.

**Comment by OneNov0209** [comment]
[genesis.json](https://github.com/BlockXLabs/blockx-gentx-mainnet/files/13922081/genesis.json)
this my genesis

**Comment by OneNov0209** [comment]
Screenshot 2024-01-13 010636

**Comment by OneNov0209** [comment]
image

**Comment by OneNov0209** [comment]
I have followed all your instructions, is this failing again?

**Comment by benjnp** [comment]
I think you did not use the genesis file from this one
https://github.com/BlockXLabs/networks/blob/master/chains/blockx_100-1/genesis.json

I compared the files that you sent versus this file and the one you used is much shorter.

**Comment by OneNov0209** [comment]
how to fix?

**Comment by benjnp** [comment]
Make sure to try to download the current genesis file on that link then generate your gentx using this script
https://github.com/BlockXLabs/BlockX-Genesis-Mainnet1/blob/main/init.sh

Though if it will be too hassle for you, its ok not to be part of the initial or genesis validators. We're open for anyone to join in right after anyway then we'll just send the allocated tokens to you once you have your node setup.

**Comment by OneNov0209** [comment]
do I have to do it all over again?

**Comment by OneNov0209** [comment]
If that's the case, I'll repeat it...

**Comment by benjnp** [comment]
Can you try:
1) Clear the data folder except priv_validator_state.json
2) run the init.sh (https://github.com/BlockXLabs/BlockX-Genesis-Mainnet1/blob/main/init.sh), replacing it with your values like validator name (moniker).
3) Replace your genesis file with the long version such as this (https://github.com/BlockXLabs/networks/blob/master/chains/blockx_100-1/genesis.json)
4) Do the blockxd add-genesis-account <your address coming from the generated account when you ran the init.sh> 100000000000000000000000abcx --keyring-backend file
5) Since the init.sh has your gentx, try to add your gentx using the blockx collect-gentxs command
6) Then blockxd start


Once that one turns out to be alright then it means you're all good then you can submit your gentx. I'll be heading to sleep now so I'll check again after around 6 hours or so.

**Comment by OneNov0209** [comment]
ok i will try again

**Comment by benjnp** [comment]
Hi,

Unfortunately it is not working and we have to go ahead with finalizing the genesis file so that everyone has enough time to download and run it. We'll put your tokens in a reserve balance for the 2 remaining validators so that after the genesis we can resume the troubleshooting and allocate the tokens to you still.

Thanks

**Comment by benjnp** [comment]
Hi,

Unfortunately it is not working and we have to go ahead with finalizing the genesis file so that everyone has enough time to download and run it. We'll put your tokens in a reserve balance for the 2 remaining validators so that after the genesis we can resume the troubleshooting and allocate the tokens to you still.

Thanks

**Comment by OneNov0209** [comment]
Please check one more

**Comment by OneNov0209** [comment]
Screenshot_2024-01-13-10-55-44-448-edit_com server auditor ssh client

I think this work

**Comment by benjnp** [comment]
Where is your new gentx?

**Comment by OneNov0209** [comment]
Already mate

**Review by benjnp — APPROVED** [review]
Great, it worked

**Comment by OneNov0209** [comment]
Thanks mate,

**Comment by OneNov0209** [comment]
Need fill form Again?

**Pull request merged**
