### PR TITLE
Update vinjan.json

### PR DESCRIPTION
**Pull request by vinjan23**
… to gentx-vinjan.json

### CODE REVIEW

**Comment by benjnp** [comment]
Did you try it on your end?

**Comment by benjnp** [comment]
It still didn't work if pasted to the long genesis.json

**Comment by benjnp** [comment]
Did you change something? I tried the latest file but still having errors

**Comment by vinjan23** [comment]
> Did you change something? I tried the latest file but still having errors

No, just replace with new genesis

**Comment by benjnp** [comment]
Did you try your gentx to add to this genesis file?
https://github.com/BlockXLabs/networks/blob/master/chains/blockx_100-1/genesis.json

**Comment by vinjan23** [comment]
> Did you try your gentx to add to this genesis file? https://github.com/BlockXLabs/networks/blob/master/chains/blockx_100-1/genesis.json

no

**Comment by benjnp** [comment]
This is one way to test if you have your gentx right

Replace your genesis file with this one (https://github.com/BlockXLabs/networks/blob/master/chains/blockx_100-1/genesis.json). Then do a
blockxd add-genesis-account{your address} 100000000000000000000000abcx --keyring-backend file

Then if you have your gentx with you, do a 'blockxd collect-gentxs' command.

Once all done then do a blockxd start, see what will happen.
It should show something like this
3:14PM INF Genesis time is in the future. Sleeping until then... genTime=2024-01-15T12:00:01Z server=node
3:14PM INF Starting pprof server laddr=localhost:6060 server=node

**Comment by vinjan23** [comment]
> blockxd collect-gentxs

5:12PM INF Version info block=11 p2p=8 server=node tendermint_version=v0.34.20
5:12PM INF This node is not a validator addr=5CE0FFC866D827291340853C5FE6933BB052A15E module=consensus pubKey=18pypvAJ6JuNc7+iOC+3NypO+mgivkuS+g11EQ4QAB0= server=node
5:12PM INF P2P Node ID ID=428c904175626b82f41f4d829dedb18d72d6b100 file=/root/.blockxd/config/node_key.json module=p2p server=node
5:12PM INF Adding persistent peers addrs=[] module=p2p server=node
5:12PM INF Adding unconditional peer ids ids=[] module=p2p server=node
5:12PM INF Add our address to book addr={"id":"428c904175626b82f41f4d829dedb18d72d6b100","ip":"0.0.0.0","port":26656} book=/root/.blockxd/config/addrbook.json module=p2p server=node
5:12PM INF service start impl=Node msg={} server=node
5:12PM INF Genesis time is in the future. Sleeping until then... genTime=2024-01-15T12:00:01Z server=node
5:12PM INF Starting pprof server laddr=localhost:6060 server=node

**Comment by benjnp** [comment]
Is your gentx included in there when you ran the collect-gentxs command?

Try to clear your data folder by going to .blockxd/data
Remove everything except the priv_validator_state.json
Then check your priv_validator_state.json, make sure it only has this
{
"height": "0",
"round": 0,
"step": 0
}

Then try to run blockxd start again

**Comment by benjnp** [comment]
Because when I tried it, I'm getting an error

**Comment by vinjan23** [comment]
> blockxd start

5:37PM INF This node is a validator addr=5CE0FFC866D827291340853C5FE6933BB052A15E module=con                                                   sensus pubKey=18pypvAJ6JuNc7+iOC+3NypO+mgivkuS+g11EQ4QAB0= server=node
5:37PM INF P2P Node ID ID=428c904175626b82f41f4d829dedb18d72d6b100 file=/root/.blockxd/confi                                                   g/node_key.json module=p2p server=node
5:37PM INF Adding persistent peers addrs=[] module=p2p server=node
5:37PM INF Adding unconditional peer ids ids=[] module=p2p server=node
5:37PM INF Add our address to book addr={"id":"428c904175626b82f41f4d829dedb18d72d6b100","ip                                                   ":"0.0.0.0","port":19656} book=/root/.blockxd/config/addrbook.json module=p2p server=node
5:37PM INF service start impl=Node msg={} server=node
5:37PM INF Genesis time is in the future. Sleeping until then... genTime=2024-01-15T12:00:01                                                   Z server=node
5:37PM INF Starting pprof server laddr=localhost:19060 server=node

**Comment by benjnp** [comment]
Can you resubmit your gentx?

**Review by benjnp — COMMENTED** [review]
Sorry but for some reason, it is not working after adding this to the main genesis file

**Comment by benjnp** [comment]
Can you try again on your end by clearing the data folder except for the priv_validator_state.
Then check the values of the priv_validator_state and see if they're something like this
{
"height": "0",
"round": 0,
"step": 0
}

Then run the blockxd start.
Also send me a screenshot of what happens after the blockxd collect-gentxs and when you do the 
blockxd add-genesis-account blockx1q47n6l07z8l6mdfltg8948st8tgpvpv7f250zp 100000000000000000000000abcx --keyring-backend file

Thanks

**Comment by vinjan23** [comment]
> Can you try again on your end by clearing the data folder except for the priv_validator_state. Then check the values of the priv_validator_state and see if they're something like this { "height": "0", "round": 0, "step": 0 }
> 
> Then run the blockxd start. Also send me a screenshot of what happens after the blockxd collect-gentxs and when you do the blockxd add-genesis-account blockx1q47n6l07z8l6mdfltg8948st8tgpvpv7f250zp 100000000000000000000000abcx --keyring-backend file
> 
> Thanks

blockx
blockx1
blockx2
blockx3
now error

**Comment by benjnp** [comment]
Yes that means that the gentx that you're using is a mismatch with the genesis file that the rest of the validators are using.

**Comment by benjnp** [comment]
Can you try to follow this one?
https://github.com/BlockXLabs/BlockX-Genesis-Mainnet1/blob/main/init.sh

Try to see if the gentx created in running that will work

**Comment by benjnp** [comment]
Though if it will be too hassle for you, its ok not to be part of the initial or genesis validators. We're open for anyone to join in right after anyway then we'll just send the allocated tokens to you once you have your node setup.

**Comment by vinjan23** [comment]
im using init.sh

**Comment by benjnp** [comment]
That's weird especially it now just down to 2 validators having the issue. Can you try:
1) Clear the data folder except priv_validator_state.json
2) run the init.sh
3) Replace your genesis file with the long version such as this (https://github.com/BlockXLabs/networks/blob/master/chains/blockx_100-1/genesis.json)
4) Do the blockxd add-genesis-account <your address> 100000000000000000000000abcx --keyring-backend file
5) Since the init.sh has your gentx, try to add your gentx using the blockx collect-gentxs command
6) Then blockxd start


Once that one turns out to be alright then it means you're all good then you can submit your gentx. I'll be heading to sleep now so I'll check again after around 6 hours or so.

**Review by benjnp — COMMENTED** [review]
This one didn't work, I recognized that the address is the same. Did you try the steps mentioned in the previous comment regarding trying to redo?

**Comment by vinjan23** [comment]
> This one didn't work, I recognized that the address is the same. Did you try the steps mentioned in the previous comment regarding trying to redo?

Need to change address ?

**Pull request closed without merging**
