### PR TITLE
Resubmit Gentx RoomIT

### PR DESCRIPTION
**Pull request by roomit-xyz**

### CODE REVIEW

**Review by benjnp — COMMENTED** [review]
Still having errors upon adding this gentx. Have you tried it locally?
Try to download the current genesis.json first 
https://github.com/BlockXLabs/networks/blob/master/chains/blockx_100-1/genesis.json

then add your gentx
then blockxd collect-gentxs
then blockxd start

Please try if you won't encounter any issues.

Thanks

**Comment by roomit-xyz** [comment]
We Got Error The address not unknown

```
M INF service start impl=PubSub module=pubsub msg={} server=node
9:53AM INF service start impl=IndexerService module=txindex msg={} server=node
9:53AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 server=node software-version=
9:53AM INF ABCI Replay Blocks appHeight=0 module=consensus server=node stateHeight=0 storeHeight=0
panic: fee payer address: blockx16am9xxy7q4yw5l9zx76zqm2p3ne8e6znc9eknr does not exist: unknown address

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/genutil.DeliverGenTxs({{0x2c5fc38, 0xc000130038}, {0x2c6f6c0, 0xc000c7ce80}, {{0x0, 0x0}, {0xc001168800, 0xc}, 0x0, {0x0, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.7/x/genutil/gentx.go:110 +0x274
github.com/cosmos/cosmos-sdk/x/genutil.InitGenesis(...)
	github.com/cosmos/cosmos-sdk@v0.45.7/x/genutil/genesis.go:18
```

```
lockxd collect-gentxs
CollectTxs-1, called from github.com/cosmos/cosmos-sdk@v0.45.7/x/genutil/collect.go#32
Error: failed to get genesis app state from config: account blockx16am9xxy7q4yw5l9zx76zqm2p3ne8e6znc9eknr balance not in genesis state: map[blockx103v804tg5ysnqfty5y500zmejffm3sgtqx64y3:{Address:blockx103v804tg5ysnqfty5y500zmejffm3sgtqx64y3 Coins:10000000000000000000000abcx} blockx1082x3ppc4eazwr8ltc07tzmjqk098nj7ygqfws:{Address:blockx1082x3ppc4eazwr8ltc07tzmjqk098nj7ygqfws Coins:10000000000000000000000abcx} blockx10melmlm2qph87l7akhjnx82rj36hrv75j6e385:{Address:blockx10melmlm2qph87l7akhjnx82rj36hrv75j6e385 Coins:10000000000000000000000abcx} blockx1293jf92xpkjejxfqtv0y57rkqd5drkkt43lz5t:{Address:blockx1293jf92xpkjejxfqtv0y57rkqd5drkkt43lz5t Coins:10000000000000000000000abcx} blockx15ypwsys4k9zzf35ceqwklu8kamxf48pkh2lmjx:{Address:blockx15ypwsys4k9zzf35ceqwklu8kamxf48pkh2lmjx Coins:10000000000000000000000abcx} blockx1663dtevplvuww3gl2lj3c30gru3pr07eyv9pa6:{Address:blockx1663dtevplvuww3gl2lj3c30gru3pr07eyv9pa6 Coins:10000000000000000000000abcx} blockx16wzfw094vx9cg98dezalsfythtv24pjl2x226n:{Address:blockx16wzfw094vx9cg98dezalsfythtv24pjl2x226n Coins:10000000000000000000000abcx} blockx17azddlnt58alt93axsvk9cr9fhl8gt9xxpkrr8:{Address:blockx17azddlnt58alt93axsvk9cr9fhl8gt9xxpkrr8 Coins:10000000000000000000000abcx} blockx17lsrsqqczn8a24asvc4le60auhxgfcr9lntuqj:{Address:blockx17lsrsqqczn8a24asvc4le60auhxgfcr9lntuqj Coins:10000000000000000000000abcx} blockx184z2kk3x22y3kyqzp5j64esp3xhtucu80xsvyf:{Address:blockx184z2kk3x22y3kyqzp5j64esp3xhtucu80xsvyf Coins:100000000000000000000000abcx} blockx1899tsdvzgvzeqvglku3nccrlcqf0u4vyh4p5wf:{Address:blockx1899tsdvzgvzeqvglku3nccrlcqf0u4vyh4p5wf Coins:10000000000000000000000abcx} blockx18a37hx5e6aez98cawjpq2n6wgtg8ujdff2enlw:{Address:blockx18a37hx5e6aez98cawjpq2n6wgtg8ujdff2enlw Coins:10000000000000000000000abcx} blockx18u0tcsw532ur4hg24qahwgqhv69uvy6n7jd33l:{Address:blockx18u0tcsw532ur4hg24qahwgqhv69uvy6n7jd33l Coins:10000000000000000000000abcx} blockx18zsyf3eqzatqamljj9hgk4sn4nx7r
````

If we check wallet

```
blockxd keys list
Enter keyring passphrase:
- name: roomit
  type: local
  address: blockx16am9xxy7q4yw5l9zx76zqm2p3ne8e6znc9eknr
  pubkey: '{"@type":"/ethermint.crypto.v1.ethsecp256k1.PubKey","key":"Aokxgmd/IHj+C/sYdmEczIMf3SlqCtEGDP7afRVYUYpi"}'
  mnemonic: ""

```

Client
```
 head .blockxd/config/client.toml
# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

###############################################################################
###                           Client Configuration                            ###
###############################################################################

# The network chain ID
chain-id = "blockx_100-1"
```

I use generate use init.sh official blockx

**Comment by benjnp** [comment]
You have to do this first
blockxd add-genesis-account blockx16am9xxy7q4yw5l9zx76zqm2p3ne8e6znc9eknr 100000000000000000000000abcx --keyring-backend file

before you do the blockxd collect-gentxs

**Comment by roomit-xyz** [comment]
Dear Team,

Yes its works now. Please kindly for review our Gentx. We have already updated wtih newer.

https://github.com/BlockXLabs/blockx-gentx-mainnet/commit/21eeab1bd6e7ad6d0ebf0879c26cd2fdfc296468

```
Jan 12 11:01:10 blockx.mainnet.roomit-pve-01.xyz blockxd[216408]: 11:01AM INF Completed ABCI Handshake - Tendermint and App are synced appHash= appHeight=0 module=consensus server=node
Jan 12 11:01:10 blockx.mainnet.roomit-pve-01.xyz blockxd[216408]: 11:01AM INF Version info block=11 p2p=8 server=node tendermint_version=v0.34.20
Jan 12 11:01:10 blockx.mainnet.roomit-pve-01.xyz blockxd[216408]: 11:01AM INF This node is a validator addr=3F5BFB7D372E9E27E2454AEA6E08B6AD3CA83654 module=consensus pubKey=QjxR3T9wSbIm+jVrBsoqm+sQgncJcGySZHGduwh59TQ= server=node
Jan 12 11:01:10 blockx.mainnet.roomit-pve-01.xyz blockxd[216408]: 11:01AM INF P2P Node ID ID=e56cc72b6f947c78c29611f567bf359e6ab450d9 file=/app/mainnet/blockx/.blockxd/config/node_key.json module=p2p server=node
Jan 12 11:01:10 blockx.mainnet.roomit-pve-01.xyz blockxd[216408]: 11:01AM INF Adding persistent peers addrs=[] module=p2p server=node
Jan 12 11:01:10 blockx.mainnet.roomit-pve-01.xyz blockxd[216408]: 11:01AM INF Adding unconditional peer ids ids=[] module=p2p server=node
Jan 12 11:01:10 blockx.mainnet.roomit-pve-01.xyz blockxd[216408]: 11:01AM INF Add our address to book addr={"id":"e56cc72b6f947c78c29611f567bf359e6ab450d9","ip":"0.0.0.0","port":26656} book=/app/mainnet/blockx/.blockxd/config/addrbook.json module=p2p server=node
Jan 12 11:01:10 blockx.mainnet.roomit-pve-01.xyz blockxd[216408]: 11:01AM INF service start impl=Node msg={} server=node
Jan 12 11:01:10 blockx.mainnet.roomit-pve-01.xyz blockxd[216408]: 11:01AM INF Genesis time is in the future. Sleeping until then... genTime=2024-01-15T12:00:01Z server=node
Jan 12 11:01:10 blockx.mainnet.roomit-pve-01.xyz blockxd[216408]: 11:01AM INF Starting pprof server laddr=localhost:6060 server=node
```

Best Regards
Dwi

**Review by benjnp — APPROVED** [review]

**Pull request merged**
