### PR TITLE
Update gentx-vinjan.json

### PR DESCRIPTION
**Pull request by vinjan23**

### CODE REVIEW

**Review by benjnp — COMMENTED** [review]
Did you try this in your local machine together with the longer genesis file?
I tried to incorporate your gentx and it didn't work.

**Comment by vinjan23** [comment]
> Did you try this in your local machine together with the longer genesis file? I tried to incorporate your gentx and it didn't work.

Maybe im use custom port in my config, ok i will change it

**Comment by benjnp** [comment]
Please try it with the longer genesis file first in your local so to be sure that the submitted gentx works perfectly

**Comment by benjnp** [comment]
Ok let me know once you submitted the new one. Thanks

**Pull request closed without merging**
